### ISSUE TITLE
Needed to add `vim.notify = require "notify"` to get pomo to use nvim-notify.

### ISSUE THREAD

**Issue by donhn** [epwalsh/pomo.nvim#10]
### 🐛 Describe the bug

Hey there, going to start with a few caveats. I'm using NvChad and know just enough to get by. I was having some trouble getting pomo to use nvim-notify until I read over the documentation for nvim-notify and saw it required vim.notify = require("notify"). 

This is the complete entry:
```
 {
    "epwalsh/pomo.nvim",
    version = "*", -- Recommended, use latest release instead of latest commit
    lazy = true,
    cmd = { "TimerStart", "TimerRepeat" },
    dependencies = {
      -- Optional, but highly recommended if you want to use the "Default" timer
      "rcarriga/nvim-notify",
      config = function()
        require("notify").setup {
          background_colour = "#000000",
        }
        vim.notify = require "notify"
      end,
    },
    opts = {},
  },
```

The background_colour issue might be unique to NvChad. Everything works well now, thanks for making this plugin!
![image](https://github.com/epwalsh/pomo.nvim/assets/38351150/f964e219-f8e3-419a-9e23-ebe1d90de3ac)

### Versions

NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794

0.4.1

**Comment by epwalsh** [comment]
Hey @donhn, good catch. #11 provides a fix so that you don't need to patch `vim.notify`, although it's fine if you do.
