### ISSUE TITLE
No notification on time out

### ISSUE THREAD

**Issue by qbnil** [epwalsh/pomo.nvim#17]
### 🐛 Describe the bug

It could not be a bug, but it's what i'm really missing, there is no notification when the clock times out. It works unless i do :TimerHide - this way it doesn't send the notification in the end, it i keep it running in the right corner, it shows me that exact notificatoin i need: 
![изображение](https://github.com/epwalsh/pomo.nvim/assets/130576530/eae6ce38-0ac7-4f37-adb3-511d82b7f876), otherwise i get this error at the end: 
![изображение](https://github.com/epwalsh/pomo.nvim/assets/130576530/94f3a2fc-c09e-4d57-9cf3-1f863b656458)
Hope this gets fixed, thx for the plugin

### Versions

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
------------------------
0.4.3⏎

**Comment by epwalsh** [comment]
Hey @qbnil looks like a bug but I'm not able to reproduce. Here's what I did to try to repro:

```vim
:TimerStart 10s
:TimerHide
```

Then wait for it to expire. I do see a notification. Did you try this on `main`? There was a recent fix for a similar issue.

**Comment by epwalsh** [comment]
Hmm can you post your config and let me know what version of nvim-notify you have?

**Comment by qbnil** [comment]
Sure, this is my current pomo.lua config, my neovim-notify version is 0.4.3
require('pomo').setup({
    -- How often the notifiers are updated.
    update_interval = 1000,

    -- Configure the default notifiers to use for each timer.
    -- You can also configure different notifiers for timers given specific names, see
    -- the 'timers' field below.
    notifiers = {
        -- The "Default" notifier uses 'vim.notify' and works best when you have 'nvim-notify' installed.
        {
            name = "Default",
            opts = {
                -- With 'nvim-notify', when 'sticky = true' you'll have a live timer pop-up
                -- continuously displayed. If you only want a pop-up notification when the timer starts
                -- and finishes, set this to false.
                sticky = true,

                -- Configure the display icons:
                title_icon = "󱎫",
                text_icon = "󰄉",
                -- Replace the above with these if you don't have a patched font:
                -- title_icon = "⏳",
                -- text_icon = "⏱️",
            },
        },

        -- The "System" notifier sends a system notification when the timer is finished.
        -- Currently this is only available on MacOS.
        -- Tracking: https://github.com/epwalsh/pomo.nvim/issues/3
        { name = "System" },

        -- You can also define custom notifiers by providing an "init" function instead of a name.
        -- See "Defining custom notifiers" below for an example 👇
        -- { init = function(timer) ... end }
    },

    -- Override the notifiers for specific timer names.
    timers = {
        -- For example, use only the "System" notifier when you create a timer called "Break",
        -- e.g. ':TimerStart 2m Break'.
        Break = {
            { name = "System" },
        },
    },
})

**Comment by qbnil** [comment]
![image](https://github.com/epwalsh/pomo.nvim/assets/130576530/2b4501e9-4b08-4989-8024-15233c08b262)
i also started to get this error when doing :TimerStart 10s break

**Comment by epwalsh** [comment]
0.4.3? I'm guessing that's pomo.nvim, not nvim-notify. Also, as it says in the error message and the readme, the system notifier is only implemented for MacOS.

**Comment by qbnil** [comment]
> 0.4.3? I'm guessing that's pomo.nvim, not nvim-notify. Also, as it says in the error message and the readme, the system notifier is only implemented for MacOS.
Gotcha, fixed the break thing. But the no matching notification found to replace still appears
