### ISSUE TITLE
'sticky = false' for Default opts = {} causes notify-send on TimerDone.

### ISSUE THREAD

**Issue by wikbon** [epwalsh/pomo.nvim#26]
### 🐛 Describe the bug

Good time of the day to you! Copied all of the settings into pomo.lua which is inside lua/plugins dir. 
When I set value of 'sticky' to 'false' in 'opts' for 'Default' it works as intended and makes Timer notification appear on start, disappear until it's done and appear again to tell it's done. But it also causes a system notification to appear. I've looked through notifiers/system.lua and default.lua, and seeing how it's implemented in System I can not figure out if it was intended for Default to also call  '[[notify-send' when 'sticky' is set to 'false'.  I would appreciate your help with fixing it, or if you could explain to me where is it implemented, if it is indeed the intended behavior. 
![2024-05-23-21-56-21](https://github.com/epwalsh/pomo.nvim/assets/49800570/5d1cbe77-f0d7-44af-bf29-71b35202c733)

### Versions

$ nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

$ nvim --headless -c 'lua print(require("pomo.version"))' -c q
0.6.0

**Comment by epwalsh** [comment]
Hey @wikbon, each timer uses all of the notifiers configured, so if you don't want the system notifier, just remove that from your config. Does that answer your question?

**Comment by wikbon** [comment]
huh, i could swear when i ran with sticky = true i did not receive any system notification. But now that I've checked again it's actually there. my bad, Sorry for that!  I appreciate the response, and the work on the pomo and obsidian, they both are Great, thank you very much!
