### ISSUE TITLE
Issues · epwalsh/pomo.nvim · GitHub

### ISSUE THREAD

**Issue by bakerbrandond** [epwalsh/pomo.nvim#4]
Would it be out of scope to integrate with [tmux-pomodor-plus](https://github.com/olimorris/tmux-pomodoro-plus)?

**Comment by epwalsh** [comment]
Probably out of scope and from a quick look it doesn't seem like there would be an easy way to integrate.

**Comment by bakerbrandond** [comment]
Thanks, great plugin.  I'll still give it a try.
